sudo : required
services:
  - docker


script:
  - docker build -t node:latest .
  - docker images node:latest


before_deploy:
  - docker login -u "$DOCKER_USER" --password-stdin
  - echo "$DOCKER_USER"
  - echo "$DOCKER_PASS"
  - echo $DOCKER_USER

deploy:
  provider: script
  script: docker push node:latest
  on:
    branch: master
