sudo : required
services:
  - docker
env:
  - DOCKER_USER = jeevanadocker123

script:
  - docker build -t node:latest .
  - docker images node


before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  - echo "$DOCKER_USER"
  - echo "$DOCKER_PASS"
  - echo $DOCKER_USER

deploy:
  provider: script
  script: docker push jeevanadocker123/node:latest
  on:
    branch: master
