sudo : required
services:
  - docker
script:
  - docker build -t jeevanadocker123/node .
  - docker images jeevanadocker123
before_deploy:
  - docker login --username jeevanadocker123 --password-stdin
deploy:
  provider: script
  script: docker push jeevanadocker123/node
  on:
    branch: master
